### ISSUE TITLE
to javascript

### ISSUE THREAD

**Issue by giacco** [fieryapi/node-js-samples#1]
Javascript has not require('https')..
Can anyone tell me ho can rewrite login function in javascript?
I have also post the same question here : http://fieryforums.efi.com/showthread.php/7052-javascript-Login
but no answer..

**Comment by namcha** [comment]
I have some Javascript only samples on <https://jsfiddle.net/namcha/yjx819kr/> and <https://jsfiddle.net/namcha/7qefcqft/>. The limitation you might encounter using Javascript code only are CORS (not fully supported in Fiery API) and handshake on https (due to self-signed certificate).

**Comment by giacco** [comment]
thank you for you're answer.
the examples were very useful, however I am still getting the same eror about CORS.
How can I pervent this? 
I need only two function..
One is log in and one to get joblog from live/v3/accounting..
There is no way to do this in JS ?

**Comment by namcha** [comment]
Can you share the error message on CORS and the browser you use? Also, make sure your web app is hosted in https since CORS does not allow communication from http to https.

Currently, we do not have full CORS support in Fiery API so you might have to wrap the web app as a standalone app with Electron or NW.js which let you modify CORS behavior.

**Comment by giacco** [comment]
I' ll post the screen of chrome and firefox console, the browser I am usign to test web app.
In Chrome login function doesn't work in firefox yes, but firefox stops when try to GET job log from live/v3/accounting..
My script JS is substantially an hacked version of youre, I only change infoApi function..

![capture_firefox](https://user-images.githubusercontent.com/19101439/36142567-c3369d20-10a8-11e8-890f-142ec3d095db.PNG)
![capture_google_chrome](https://user-images.githubusercontent.com/19101439/36142568-c3d49b92-10a8-11e8-9527-dcc81d0c481f.PNG)

Maybe the problem is that I have not an ssl certificate installed in my web server, but my app must run in LAN.
I need to install an ssl certificate anyway?

**Comment by namcha** [comment]
For FireFox error, make sure your XHR has `xhr_obj.withCredentials = true;` before you send the request so the cookie session is set in the request.
![firefox network cors](https://user-images.githubusercontent.com/2081816/36169927-a0905f52-10f5-11e8-8376-129594b2ea4b.png)

For Chrome, you will need to open a new tab and navigate to the server address on `https://192.168.0.187` and confirm that the browser can navigate to the site. The user will have to do this on each session since the Fiery server is using self-signed certificate.
![chrome network cors](https://user-images.githubusercontent.com/2081816/36169936-a6dd64ae-10f5-11e8-8eaa-aea0dc6698d6.png)

I tried http://jsfiddle.net and it seems to work. You might not need to install the certificate on your server.

**Comment by giacco** [comment]
thanks for the answer. Now I am able to do login using chrome.
Anyway I'm still getting the same error about CORS when I try to GET from  ../live/v4/accounting...
It seems that something goes wrong during the handshake becouse I cant reuse cookie session.
Mayby I am setting XHR withCredential = true in the wrong way..
I can not explain why this appens in my code .. It is similar to yours.. I'll post the index..Mayby you are more able to find the wrong point..
Thanks in anyway.

[index.zip](https://github.com/fieryapi/node-js-samples/files/1727104/index.zip)

**Comment by namcha** [comment]
In your code, the login and accounting API are not using the same version URL so it ends up with 401. The sample I have is based on v1 URL.

I modify your code for the login to use v4 and also update the parser logic since we have a different response structure on v4 URL.
[index.zip](https://github.com/fieryapi/node-js-samples/files/1729203/index.zip)

**Comment by giacco** [comment]
Thank you for your help namcha.
Now I can go on with my work.
